# Generated by Django 5.1.4 on 2025-01-07 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='experiences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('experience', 'Experience'), ('skill', 'Skill')], max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('link', models.URLField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('alternate_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
